# Force rebuild 2026-04-07
services:
  - type: web
    name: auto-scheduling
    env: python
    pythonVersion: 3.11
    region: oregon
    plan: free
    buildCommand: |
      set -e
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      python render_create_superuser.py
    startCommand: gunicorn ASSIST.wsgi:application
    envVars:
      - key: SECRET_KEY
        fromDatabase:
          name: auto_scheduling_db
          property: secret_key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "auto-scheduling-7.onrender.com,localhost,127.0.0.1"

databases:
  - name: auto_scheduling_db
    databaseName: auto_scheduling
    user: postgres_user # Force Rebuild
