services:
  - type: web
    name: auto-scheduling
    env: python
    pythonVersion: 3.11
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn ASSIST.wsgi:application
    envVars:
      - key: SECRET_KEY
        fromDatabase:
          name: auto_scheduling_db
          property: secret_key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "auto-scheduling-5.onrender.com,localhost,127.0.0.1"

databases:
  - name: auto_scheduling_db
    databaseName: auto_scheduling
    user: postgres_user
