# Force rebuild 2026-04-07
services:
  - type: web
    name: auto-scheduling
    env: python
    pythonVersion: 3.11
    region: oregon
    plan: free
    buildCommand: |
      set -e
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      python render_create_superuser.py
    startCommand: gunicorn ASSIST.wsgi:application
    envVars:
      - key: SECRET_KEY
        fromDatabase:
          name: auto_scheduling_db
          property: secret_key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "auto-scheduling-7.onrender.com,localhost,127.0.0.1"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp.resend.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: "apikey"
      - key: EMAIL_HOST_PASSWORD
        value: "re_VwrppCai_PA6bhEJuBxq5DzhoBD17J9wq"
      - key: EMAIL_TIMEOUT
        value: "10"
      - key: DEFAULT_FROM_EMAIL
        value: "msnbaldonado@tip.edu.ph"  # Updated to your real sender email

databases:
  - name: auto_scheduling_db
    databaseName: auto_scheduling
    user: postgres_user # Force Rebuild
