# Generated by Django 5.0.6 on 2026-04-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_faculty_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='professional_title',
            field=models.CharField(blank=True, choices=[('', '-- Select Title --'), ('Dr.', 'Dr. (Doctor)'), ('Engr.', 'Engr. (Engineer)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='highest_degree',
            field=models.CharField(blank=True, choices=[('', '-- Select Degree --'), ('Bachelor\'s Degree', 'Bachelor\'s Degree'), ('Master\'s Degree', 'Master\'s Degree'), ('Doctoral Degree', 'Doctoral Degree')], default='', max_length=100),
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='specialization',
        ),
        migrations.AddField(
            model_name='faculty',
            name='specialization',
            field=models.CharField(blank=True, choices=[('computer_networking', 'Computer Networking'), ('digital_electronics', 'Digital Electronics'), ('software_dev', 'Software Development'), ('machine_learning', 'Machine Learning'), ('cyber_security', 'Cyber Security'), ('system_administration', 'System Administration'), ('computer_architecture', 'Computer Architecture'), ('embedded_systems', 'Embedded Systems'), ('other', 'Other')], default='', max_length=50),
        ),
    ]
